#!/usr/bin/env node
// Fetch a YouTube video's transcript (subtitles) as clean plain text, for summarizing.
// Uses yt-dlp to download ONLY the caption track (no video/audio), then converts the
// VTT to readable text in Node — so the model's context isn't filled with cue
// timings and markup. No Python/ffmpeg needed.
//
// Usage:
//   node transcript.mjs "<youtube url or video id>" [--lang en]
//
// Prefers human-authored subtitles; falls back to auto-generated captions.
import { spawnSync } from "node:child_process";
import { mkdtempSync, readdirSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

function die(msg) {
  console.error(`youtube: ${msg}`);
  process.exit(1);
}

function ytdlp(args) {
  const r = spawnSync("yt-dlp", args, { encoding: "utf8", maxBuffer: 64 * 1024 * 1024 });
  if (r.error) die(`could not run yt-dlp (${r.error.code === "ENOENT" ? "not installed" : r.error.message})`);
  return r;
}

function fetchSubs(url, lang, dir, auto) {
  return ytdlp([
    "--skip-download",
    "--no-playlist",
    "--no-warnings",
    auto ? "--write-auto-subs" : "--write-subs",
    "--sub-langs", `${lang}.*,${lang}`,
    "--sub-format", "vtt",
    "--write-info-json",
    "-o", "%(id)s.%(ext)s",
    "-P", dir,
    url,
  ]);
}

const findFile = (dir, ext) => readdirSync(dir).find((f) => f.endsWith(ext));

// Convert a WebVTT caption file to readable text. YouTube auto-captions roll: each
// cue repeats the previous line and grows it, so we drop markup, then merge lines
// that are duplicates or prefixes of the next.
function vttToText(vtt) {
  const out = [];
  for (let line of vtt.split(/\r?\n/)) {
    const t = line.trim();
    if (!t || t.startsWith("WEBVTT") || t.startsWith("Kind:") || t.startsWith("Language:")) continue;
    if (t.startsWith("NOTE") || t.includes("-->")) continue;
    line = line
      .replace(/<[^>]+>/g, "") // inline word-timing tags
      .replace(/&nbsp;/gi, " ")
      .replace(/&amp;/gi, "&").replace(/&lt;/gi, "<").replace(/&gt;/gi, ">")
      .replace(/&#39;|&apos;/gi, "'").replace(/&quot;/gi, '"')
      .trim();
    if (!line) continue;
    if (out.length) {
      const prev = out[out.length - 1];
      if (line === prev || prev.startsWith(line)) continue; // duplicate / shrunk
      if (line.startsWith(prev)) { out[out.length - 1] = line; continue; } // grew
    }
    out.push(line);
  }
  return out.join("\n");
}

// ---- parse args ----
let url, lang = "en";
for (let i = 0; i < process.argv.length - 2; i++) {
  const a = process.argv[i + 2];
  if (a === "--lang") lang = process.argv[i + 3] ?? "en", i++;
  else if (!url) url = a;
}
if (!url) die('usage: transcript.mjs "<youtube url or video id>" [--lang en]');
if (/^[A-Za-z0-9_-]{11}$/.test(url)) url = `https://www.youtube.com/watch?v=${url}`;

const dir = mkdtempSync(join(tmpdir(), "yt-"));
try {
  let r = fetchSubs(url, lang, dir, false);
  let auto = false;
  let vtt = findFile(dir, ".vtt");
  if (!vtt) {
    r = fetchSubs(url, lang, dir, true);
    auto = true;
    vtt = findFile(dir, ".vtt");
  }
  if (!vtt) {
    const errLine = (r.stderr || "").split("\n").find((l) => /ERROR/i.test(l));
    if (errLine) die(errLine.replace(/^ERROR:\s*/i, "").trim());
    die(`no ${lang} subtitles or captions available for this video`);
  }

  const infoFile = findFile(dir, ".info.json");
  const meta = infoFile ? JSON.parse(readFileSync(join(dir, infoFile), "utf8")) : {};
  const text = vttToText(readFileSync(join(dir, vtt), "utf8"));

  const CAP = 40000; // ~10k tokens — keep room in the context window for the summary
  const truncated = text.length > CAP;
  console.log(JSON.stringify({
    id: meta.id,
    title: meta.title,
    uploader: meta.uploader ?? meta.channel,
    durationSeconds: meta.duration,
    url: meta.webpage_url ?? url,
    lang,
    autoGenerated: auto,
    chars: text.length,
    truncated,
    transcript: truncated ? text.slice(0, CAP) + "\n…[truncated — long video]" : text,
  }, null, 2));
} finally {
  rmSync(dir, { recursive: true, force: true });
}
